##########################################################
# Packages
##########################################################
library(CARBayes); library(coda); library(largeList)
library(ggplot2); library(ggmap)
library(rgeos); library(maptools)
library(spdep); library(sp); library(sf)
library(rgdal); library(raster); library(spatstat)
library(plotrix); library(caret); library(corrplot)
library(GADMTools); library(PrevMap); library(tmap)
library(magrittr); library(dplyr); library(spatialEco)
library(reshape2); library(RColorBrewer)

##########################################################
# Data
##########################################################

## Run shapefile/covariate and survey data code first, or 
## Use predicted estimates generated by our group: 

setwd("~/MalDrugRes_SSA/Observed_Prevalence/crt_time1") ## change to marker & time period of interest
ctry_shps1 <-  shapefile("ctry_shps1.shp") ## read in shapefile with merged covariate and survey data
ctry_shps1 <- ctry_shps1[!is.na(ctry_shps1$mPPR_06),] ## remove non-endemic malaria regions from analysis

## Clean covariate data
ctry_shps1$mnPv_06[ctry_shps1$mnPv_06=="NaN"] <- 0 ## assume no P. vivax in regions where val=NA
ctry_shps1$mnPv_14[ctry_shps1$mnPv_14=="NaN"] <- 0 ## assume no P. vivax in regions where val=NA
ctry_shps1$pres_pv_06 <- ifelse(ctry_shps1$mnPv_06>0,1,0) ## add presence/absence var. for P.vivax
ctry_shps1$pres_pv_14 <- ifelse(ctry_shps1$mnPv_14>0,1,0) ## add presence/absence var. for P.vivax

## Change variable names for clarity (some variable names abbreviated/scrambled in writing OGR)
ctry_shps1$seasonality <- ctry_shps1$sesnlty ## may also be called rnfll_2 in mcmc output 
ctry_shps1$city_access <- ctry_shps1$access ## may also be called roads2 in mcmc output
ctry_shps1$PvPR_06 <- ctry_shps1$mnPv_06; ctry_shps1$PvPR_14 <- ctry_shps1$mnPv_14
ctry_shps1$PfPR_06 <- ctry_shps1$mPPR_06; ctry_shps1$PfPR_14 <- ctry_shps1$mPPR_14
ctry_shps1$drg_pl_al <- ctry_shps1$drg_pl_l ## may also be called drg_pl_1
ctry_shps1$drg_pl_asaq <- ctry_shps1$drg_pl_s  ## may also be called drg_pl_2
ctry_shps1$drg_pl_multi <- ctry_shps1$drg_pl_m  ## may also be called drg_pl_3

## Prep data for CAR analysis by converting to df
prev_sp <- as(ctry_shps1, "SpatialPolygons")   
prev_df <- slot(ctry_shps1, "data")        
prev_df$N.test <- prev_df$N                
prev_df$N.test[is.na(prev_df$N.test)] <- 1
trials <- prev_df$N.test

##########################################################
# Nearest neighbor definition
##########################################################
spatial_neighbors<-poly2nb(prev_sp, queen=TRUE, snap=sqrt(0))
spatial_neighbors_mat<-nb2mat(spatial_neighbors, zero.policy=TRUE, style="B")

##########################################################
## Model. CAR-Leroux model selection
##########################################################

formula_time1= prev_df$Mut ~ scale(cbind(prev_df$PfPR_06, prev_df$PvPR_06, 
                                         prev_df$ACTcv06, prev_df$itns_06,
                                         prev_df$seasonality, log(prev_df$city_access)))

formula_time2= prev_df$Mut ~ scale(cbind(prev_df$PfPR_14, prev_df$PvPR_14, 
                                         prev_df$ACTcv14, prev_df$itns_14, 
                                         prev_df$seasonality, log(prev_df$city_access))) 
                                         prev_df$drg_pl_asaq + prev_df$drg_pl_multi
## Modifications and notes: 
## Add or remove variables of interest from above formulas; scale continuous variables  
## Reference first-line policy is AL                                        
## Troubleshooting: If P. vivax covar. is causing problems, use presence/absence of P. vivax instead (binary var.; do not scale)

model= S.CARleroux(  formula=formula_time1, family="binomial", 
                     trials=trials, W=spatial_neighbors_mat, 
                     burnin=100000, 
                     n.sample=1100000, 
                     thin = 100,
                     prior.tau2 = c(0.01, 0.01),
                     prior.var.beta = rep(100^2, times = 7)) ## times= no. of covariates + 1

print(model) 

#setwd("~/Predicted_Prevalence")
#saveRDS(model,file = "crt_time1_mcmc.RData")

##########################################################
# Summary of results
##########################################################

#setwd("~/MalDrugRes_SSA/Fit_Pred_Prevalence_PNAS") ## use data generated by our group or insert other
#model <- readRDS(file = "crt_time1_mcmc.RData") ## change to marker of interest

## use for time period 1
conf.ints <- as.data.frame(model$summary.results[2:7,1:3]) 
rownames(conf.ints) <- c("PfPR","PvPR","ACTcov","ITNcov","Seasonality","City_access")
plotCI(x = conf.ints$Median, ui = conf.ints$`97.5%`,li = conf.ints$`2.5%`,main="",xaxt='n',xlab="", ylab="", pch=16, lwd=2); abline(h=0, lty=2)
axis(side=1, at=1:6, labels = rownames(conf.ints),cex.axis=1,las=2)

## use for time period 2
conf.ints <- as.data.frame(model$summary.results[2:9,1:3]) 
rownames(conf.ints) <- c("PfPR","PvPR","ACTcov","ITNcov","Seasonality","City_access","AS-AQ","Both/Other")
plotCI(x = conf.ints$Median, ui = conf.ints$`97.5%`,li = conf.ints$`2.5%`,main="",xaxt='n',xlab="", ylab="", pch=16, lwd=2); abline(h=0, lty=2)
axis(side=1, at=1:8, labels = rownames(conf.ints),cex.axis=1,las=2)

##########################################################
# Calculating p_k 
##########################################################

## time period 1
covars_time1 <- cbind(rep(1,dim(prev_df)[1]), scale(cbind(prev_df$PfPR_06, prev_df$PvPR_06, prev_df$ACTcv06, 
                prev_df$itns_06, prev_df$seasonality, log(prev_df$city_access))))
p_k_1 <- matrix(nrow=10000,ncol=608)
for (k in 1:608) {
  for (iter in 1:10000) {
    x <- covars_time1[k,] %*% model$samples$beta[iter,] + model$samples$phi[iter,k]
    p_k_1[iter,k] <- exp(x)/(1+exp(x))
  } }
mean_p_k_1 <- colMeans(p_k_1)
sd_p_k_1 <- apply(p_k_1, 2, sd)

## time period 2
covars_time2 <- cbind(rep(1,dim(prev_df)[1]),scale(cbind(prev_df$PfPR_14, prev_df$PvPR_14, prev_df$ACTcv14, 
                prev_df$itns_14, prev_df$seasonality, log(prev_df$city_access))),
                prev_df$drg_pl_asaq,prev_df2$drg_pl_multi)
p_k_2 <- matrix(nrow=10000,ncol=608)
for (k in 1:608) {
  for (iter in 1:10000) {
    x <- covars_time2[k,] %*% model$samples$beta[iter,] + model$samples$phi[iter,k]
    p_k_2[iter,k] <- exp(x)/(1+exp(x))
  } }
mean_p_k_2 <- colMeans(p_k_2)
sd_p_k_2 <- apply(p_k_2, 2, sd)

prev_df$modelvals <- model$fitted.values
prev_df$N[is.na(prev_df$N)] <- 1
prev_df$modelprev <- prev_df$modelvals/prev_df$N

standdevs <- rep(NA, nrow(prev_df))
for (i in 1:ncol(model$samples$fitted)) 
{standdevs[i] <- sd(model$samples$fitted[,i]/prev_df$N[i])}
prev_df$modelsd <- standdevs

##########################################################
# Mapping
##########################################################

setwd("~/MalDrugRes_SSA/gadm")
ssa = list()
ssa$countries = c("AGO","BDI","BEN","BFA","BWA","CAF","CIV","CMR","COD","COG","ERI",
                  "ETH","GAB","GHA","GIN","GMB","GNB","GNQ","KEN","LBR","MDG","MLI","MOZ","MRT",
                  "MWI","NAM","NER","NGA","RWA","SDN","SEN","SLE","SOM","SSD","SWZ",
                  "TCD","TGO","TZA","UGA","ZAF","ZMB","ZWE","LSO")
ctry_outlines = do.call("bind", lapply(ssa$countries, function(x) raster::getData('GADM', country=x, level=0)))
ctry_shps = do.call("bind", lapply(ssa$countries, function(x) raster::getData('GADM', country=x, level=1)))
ctry_shps@data <- left_join(ctry_shps@data, prev_df, by=c("NAME_1" = "NAME_1", "NAME_0" = "NAME_0"), all.x = TRUE)
modelprev_map <- tm_shape(ctry_shps) + tm_polygons(col = "modelprev", palette="YlGnBu", breaks=seq(0,1,by=0.2)) +tm_shape(ctry_outlines) + tm_borders(col='black', lwd=2)
sd <- tm_shape(ctry_shps) + tm_polygons(col = "modelsd", palette="YlOrRd", breaks=seq(0,0.5,by=0.1)) +tm_shape(ctry_outlines) + tm_borders(col='black', lwd=2)

setwd("~/MalDrugRes_SSA/PNAS_figures")
pdf()
#print(modelprev_map) 
dev.off()

## Example for mapping a single country: 
Burkina_Faso <- ctry_shps[which(ctry_shps$NAME_0=="Burkina Faso"),]
BFmap <- tm_shape(Burkina_Faso) + 
  tm_polygons(col = "modelprev", palette="YlGnBu", breaks=seq(0,1,by=0.2))

##########################################################
# Assessing variables assoc. w. marker selection over time
##########################################################

#setwd("~/Fit_Pred_Prevalence_PNAS")
#model1 <- readRDS(file = "crt_time1_mcmc.RData")
#model2 <- readRDS(file = "crt_time2_mcmc.RData")

#setwd("~/Observed_Prevalence/crt_time1")
#ctry_shps1 <-  shapefile("ctry_shps1.shp"); ctry_shps1 <- ctry_shps1[!is.na(ctry_shps1$mPPR_06),]
#prev_df1 <- slot(ctry_shps1, "data"); prev_df1$N[is.na(prev_df1$N)] <- 1

#setwd("~/Observed_Prevalence/crt_time2")
#ctry_shps2 <-  shapefile("ctry_shps1.shp"); ctry_shps2 <- ctry_shps2[!is.na(ctry_shps2$mPPR_06),]
#prev_df2 <- slot(ctry_shps2, "data"); prev_df2$N[is.na(prev_df2$N)] <- 1

no.ADs= 608 ## number of total admin. divisions
mat1 <- matrix(data=NA, nrow=100, ncol=no.ADs) ## 100 arbitrarily chosen for simulation
mat2 <- matrix(data=NA, nrow=100, ncol=no.ADs)  

for (i in 1:no.ADs) {mat1[,i] <- sample(model1$samples$fitted[,i],100)}
for (i in 1:no.ADs) {mat2[,i] <- sample(model2$samples$fitted[,i],100)} 
for (i in 1:no.ADs) {mat1[,i] <- mat1[,i]/prev_df1$N[i]}
for (i in 1:no.ADs) {mat2[,i] <- mat2[,i]/prev_df2$N[i]}
mat1 <- mat1*10; mat2 <- mat2*10 ## scale for CAR analysis
rel.diffs <- (mat1-mat2)/mat1

prev_sp <- as(ctry_shps1, "SpatialPolygons")   
spatial_neighbors<-poly2nb(prev_sp, queen=TRUE, snap=sqrt(0))
spatial_neighbors_mat<-nb2mat(spatial_neighbors, zero.policy=TRUE, style="B")

## insert variables of interest below
conf.ints <- vector("list")
for (i in 1:100) {
  formula= diffs[i,] ~ scale(cbind(season, roads2, actcov, itncov, prev.pf)) + drpol1 + drpol2
  model= S.CARleroux(formula=formula, family="gaussian",
                     W=spatial_neighbors_mat, 
                     burnin=30000, 
                     n.sample=100000,
                     prior.tau2 = c(0.01, 0.01),
                     prior.var.beta = rep(100^2, times=7)) ## times= no. of variables
  conf.ints[[i]] <- model$summary.results[2:9,1:3] }
arr <- array(unlist(conf.ints), c(8,3,100))
ci.plot <- as.data.frame(rowMeans(arr, dims = 2))
plotCI(x = ci.plot$V1, ui = ci.plot$V3,li =ci.plot$V2, main="",
       xaxt='n',xlab="", ylab="", pch=16, lwd=2); abline(h=0, lty=2)
ci.plot$names <- c("seasonality","city access","ACT cov","ITN cov","PfPR","Pol1","Pol2")
axis(side=1, at=1:8, labels = ci.plot$names,cex.axis=1,las=2)

samples_1 <- as.matrix(model1$samples$fitted)
samples_2 <- as.matrix(model2$samples$fitted)
diffs <- matrix(NA,dim(model1$samples$fitted)[1],608)
diffs.above0 <- rep(NA, 608)
for (i in 1:608) {diffs[,i] <- samples_1[,i]/prev_df1$N[i]-samples_2[,i]/prev_df2$N[i]}
for (i in 1:608) {diffs.above0[i] <- sum(diffs[,i]>0)/dim(model1$samples$fitted)[1]}
mean(diffs.above0) ## bayesian p-value


